"""One self-contained HTML page per real-model population (2026-09-12,
requested directly: "an associated webpage that comes up with each of the
results whenever it's run on a new population so that the user can trace
over each of the lines to pinpoint the exact moment where the drop
occurs ... very simple and refined looking, with no glowing dots").

results/pages/<scenario>_<model>.html + results/pages/index.html. Each
page: the same series and numbers as that model's PDF page (it reuses
render_score_report.compute_stats, so the two cannot disagree), drawn as
inline SVG step curves with a hover crosshair: move along the time axis
and every series' S(t) is read out at that instant, with the model's
nearest drop (an episode's event time) and its diagnosed channel named.
Under the survival chart a thin rug marks every individual event time.
No libraries, no network, no animation -- a static file that opens
anywhere. Regenerated by render_score_report.py on every run; also
callable alone.

    python3 scripts/render_population_pages.py
    open results/pages/index.html
"""
import json
import html
import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from mcphysbench.branding import PUBLIC_NAME, PUBLIC_TAGLINE

ROOT = pathlib.Path(__file__).resolve().parents[1]
PAGES_DIR = ROOT / "results" / "pages"

# Paint + frame: scripts/_site_theme.py (the Midcentury research-post look,
# 2026-10-01). What follows is only what these pages add on top.
import _site_theme as T
CSS = """
.chart{border:1px solid var(--border);border-radius:8px;background:#000;overflow:hidden}
svg{display:block;width:100%;height:auto}
.readout{display:flex;flex-wrap:wrap;gap:6px 18px;font:400 16px/1.4 var(--mono);padding:10px 14px 12px;border-top:1px solid var(--border);min-height:48px;color:var(--fg)}
.readout .t{color:var(--muted)}
.legend{display:flex;flex-wrap:wrap;gap:8px 20px;font:400 16px/1.4 var(--mono);text-transform:uppercase;letter-spacing:.04em;color:var(--muted);margin:10px 0 0}
.legend span::before{content:"";display:inline-block;width:14px;height:2px;vertical-align:middle;margin-right:8px;background:currentColor}
.stackrow{display:flex;align-items:center;gap:14px;margin:8px 0}
.stackrow .lbl{flex:0 0 180px;font:400 16px/1.3 var(--mono);color:var(--muted);text-align:right;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.stackrow .segs{flex:1;display:flex;height:100%;overflow:hidden;background:var(--step2)}
.stackrow .segs i{display:flex;align-items:center;justify-content:center;height:100%;font:500 16px/1 var(--mono);color:#fff;white-space:nowrap;overflow:hidden;font-style:normal}
.stackrow .segs i.ok{background:var(--accent);color:#000}
table.readout-t td{white-space:normal;color:var(--fg2)}
.section{margin:0 0 8px}
"""

# Channel colours, the same palette as the PDF report (render_score_report.COLOR_RISK).
# User's palette (2026-09-17): purple, yellow, blue, red, orange, pink for
# R1, R2, R3, R5, R6, R7 (R4 is its own independent channel, teal).
RISK_COLOR = {"R1": "#7C3AED", "R2": "#EAB308", "R3": "#2563EB", "R4": "#0F766E", "R5": "#DC2626",
              "R6": "#F97316", "R7": "#EC4899"}
RISK_INK = {"R2": "#000"}   # dark text on the yellow segment


def _stack_bar(prof, censoring, label=None, height=14):
    """One horizontal bar per series, divided into a segment per channel
    (share of EPISODES terminated by that channel, channel colours) with
    the still-valid remainder in light grey -- the page version of the
    PDF's failure-mode chart (user, 2026-09-16: the bars dividing the
    classification of failures were a good visualizer; restored)."""
    fired = 1.0 - censoring
    segs = []
    for k, v in sorted(prof.items()):
        w = v * fired * 100
        if w <= 0:
            continue
        # Segment text is the percentage only -- the channel is its colour
        # (key at the top of the page); "R3 67%" overflowed narrow segments.
        segs.append(f'<i style="width:{w:.1f}%;background:{RISK_COLOR.get(k, "#66708a")};color:{RISK_INK.get(k, "#fff")}" title="{html.escape(k)} {w:.0f}% of episodes">'
                    f'{f"{w:.0f}%" if w >= 16 else ""}</i>')
    rest = max(0.0, censoring * 100)
    segs.append(f'<i class="ok" style="width:{rest:.1f}%" title="still valid at t_max: {rest:.0f}%">{("valid " + f"{rest:.0f}%") if rest >= 30 else (f"{rest:.0f}%" if rest >= 16 else "")}</i>')
    lab = f'<span class="lbl">{html.escape(label)}</span>' if label else ""
    return f'<div class="stackrow" style="height:{height}px">{lab}<div class="segs">{"".join(segs)}</div></div>'


def _chips(prof, censoring):
    """Failure modes as coloured chips: share of EPISODES terminated by each channel."""
    fired = 1.0 - censoring
    out = [f'<span class="chip"><i style="background:{RISK_COLOR.get(k, "#8a8a8a")}"></i>{html.escape(k)} {v * fired * 100:.0f}%</span>'
           for k, v in sorted(prof.items())]
    return "".join(out) or '<span class="modes">none</span>'

JS = """
function attach(id, series, tmax, events) {
  const svg = document.getElementById(id);
  const ro = document.getElementById(id + '-ro');
  const cross = svg.querySelector('.cross');
  const g = svg.querySelector('.plot');
  const W = +g.dataset.w, H = +g.dataset.h, x0 = +g.dataset.x0, y0 = +g.dataset.y0;
  function sAt(s, t) { let v = 1.0; for (let i = 0; i < s.t.length; i++) { if (s.t[i] <= t) v = s.S[i]; else break; } return v; }
  function fmt(v, d) { return (v === null || v === undefined || Number.isNaN(v)) ? '—' : v.toFixed(d === undefined ? 2 : d); }
  svg.addEventListener('mousemove', (ev) => {
    const r = svg.getBoundingClientRect();
    const sx = svg.viewBox.baseVal.width / r.width;
    const px = (ev.clientX - r.left) * sx;
    let t = (px - x0) / W * tmax;
    if (t < 0 || t > tmax) { cross.setAttribute('visibility', 'hidden'); return; }
    cross.setAttribute('visibility', 'visible');
    cross.setAttribute('x1', px); cross.setAttribute('x2', px);
    let parts = ['<span class="t">t = ' + fmt(t) + ' s</span>'];
    for (const s of series) parts.push('<span style="color:' + s.color + '">' + s.name + '</span> S = ' + fmt(sAt(s, t)));
    if (events && events.length) {
      let best = null;
      for (const e of events) { if (e.t <= t && (best === null || e.t > best.t)) best = e; }
      if (best) parts.push('<span class="t">last drop</span> ' + fmt(best.t) + ' s · ' + best.risk + ' · ' + best.n + ' episode' + (best.n > 1 ? 's' : ''));
      else parts.push('<span class="t">no drop yet</span>');
    }
    ro.innerHTML = parts.join('&nbsp;&nbsp;');
  });
  svg.addEventListener('mouseleave', () => { cross.setAttribute('visibility', 'hidden'); ro.innerHTML = '<span class="t">move along the curve</span>'; });
}
"""


def _step_path(t, S, x0, y0, W, H, tmax, t_end=None):
    """SVG path for a right-continuous step function on [0, tmax]."""
    pts = []
    xs = lambda tt: x0 + W * max(0.0, min(tt, tmax)) / tmax
    ys = lambda ss: y0 + H * (1.0 - ss)
    cur_s = 1.0
    pts.append(f"M{xs(0):.1f},{ys(1.0):.1f}")
    for tt, ss in zip(t, S):
        if tt > tmax:
            break
        pts.append(f"L{xs(tt):.1f},{ys(cur_s):.1f}")
        pts.append(f"L{xs(tt):.1f},{ys(ss):.1f}")
        cur_s = ss
    pts.append(f"L{xs(t_end if t_end is not None else tmax):.1f},{ys(cur_s):.1f}")
    return " ".join(pts)


def _survival_svg(sid, series, tmax, events, height=300):
    """series: list of dict(name, color, t, S, t_end). events: list of
    dict(t, risk, n) for the model's own event rug."""
    Wv, Hv = 900, height
    x0, y0, W, H = 52, 18, Wv - 52 - 18, height - 18 - 44
    parts = [f'<svg id="{sid}" viewBox="0 0 {Wv} {Hv}" xmlns="http://www.w3.org/2000/svg" role="img">']
    parts.append(f'<g class="plot" data-w="{W}" data-h="{H}" data-x0="{x0}" data-y0="{y0}">')
    # grid + axes
    for k in range(0, 5):
        yy = y0 + H * (1 - k / 4)
        parts.append(f'<line x1="{x0}" y1="{yy:.1f}" x2="{x0 + W}" y2="{yy:.1f}" stroke="rgba(255,255,255,.10)" stroke-width="1"/>')
        parts.append(f'<text x="{x0 - 8}" y="{yy + 4:.1f}" font-size="13" fill="#8a8a8a" text-anchor="end">{k / 4:.2f}</text>')
    n_ticks = int(tmax) + 1
    for k in range(0, 2 * n_ticks + 1):
        tt = k * 0.5
        if tt > tmax + 1e-9:
            break
        xx = x0 + W * tt / tmax
        parts.append(f'<line x1="{xx:.1f}" y1="{y0 + H}" x2="{xx:.1f}" y2="{y0 + H + 4}" stroke="rgba(255,255,255,.3)" stroke-width="1"/>')
        parts.append(f'<text x="{xx:.1f}" y="{y0 + H + 17}" font-size="13" fill="#8a8a8a" text-anchor="middle">{tt:g}</text>')
    parts.append(f'<text x="{x0 + W / 2:.1f}" y="{Hv - 4}" font-size="13" fill="#8a8a8a" text-anchor="middle">time (s)</text>')
    parts.append(f'<line x1="{x0}" y1="{y0}" x2="{x0}" y2="{y0 + H}" stroke="rgba(255,255,255,.25)"/>')
    parts.append(f'<line x1="{x0}" y1="{y0 + H}" x2="{x0 + W}" y2="{y0 + H}" stroke="rgba(255,255,255,.25)"/>')
    # the given prefix: nothing can fail before it ends (2026-10-07)
    px = x0 + W * min(1.0, tmax) / tmax
    parts.append(f'<rect x="{x0}" y="{y0}" width="{px - x0:.1f}" height="{H}" fill="rgba(255,255,255,.05)"/>')
    parts.append(f'<text x="{(x0 + px) / 2:.1f}" y="{y0 + 14}" font-size="13" fill="#8a8a8a" text-anchor="middle">given prefix</text>')
    # event rug (model only)
    for e in events:
        xx = x0 + W * e["t"] / tmax
        parts.append(f'<line x1="{xx:.1f}" y1="{y0 + H - 7}" x2="{xx:.1f}" y2="{y0 + H}" stroke="#A9FF3C" stroke-opacity="0.6" stroke-width="1"/>')
    for s in series:
        d = _step_path(s["t"], s["S"], x0, y0, W, H, tmax, t_end=s.get("t_end"))
        parts.append(f'<path d="{d}" fill="none" stroke="{s["color"]}" stroke-width="2" stroke-linejoin="round"/>')
        if s.get("t_end") is not None and s["t_end"] < tmax:      # censored plateau past the last event
            xs = x0 + W * s["t_end"] / tmax; ys = y0 + H * (1 - s["S"][-1] if s["S"] else 0)
            parts.append(f'<line x1="{xs:.1f}" y1="{ys:.1f}" x2="{x0 + W}" y2="{ys:.1f}" stroke="{s["color"]}" stroke-width="2" stroke-dasharray="3 5" stroke-opacity="0.6"/>')
    parts.append(f'<line class="cross" x1="0" y1="{y0}" x2="0" y2="{y0 + H}" stroke="#fff" stroke-width="1" stroke-opacity="0.6" visibility="hidden"/>')
    parts.append("</g></svg>")
    return "\n".join(parts)


def _lambda_svg(levels, height=200):
    """VI50 and RMVT vs lambda, log-x, no interaction needed."""
    import math
    Wv, Hv = 900, height
    x0, y0, W, H = 52, 18, Wv - 52 - 18, height - 18 - 44
    lams = [l["lam"] for l in levels]
    lx = lambda lam: x0 + W * (math.log2(lam) - math.log2(min(lams))) / max(1e-9, math.log2(max(lams)) - math.log2(min(lams)))
    ymax = max([l["rmvt"] for l in levels] + [l["vi50"] for l in levels if l["vi50"] != float("inf")] + [1.0]) * 1.1
    ly = lambda v: y0 + H * (1 - min(v, ymax) / ymax)
    parts = [f'<svg viewBox="0 0 {Wv} {Hv}" xmlns="http://www.w3.org/2000/svg" role="img">']
    for k in range(5):
        yy = y0 + H * (1 - k / 4)
        parts.append(f'<line x1="{x0}" y1="{yy:.1f}" x2="{x0 + W}" y2="{yy:.1f}" stroke="rgba(255,255,255,.10)"/>')
        parts.append(f'<text x="{x0 - 8}" y="{yy + 4:.1f}" font-size="13" fill="#8a8a8a" text-anchor="end">{ymax * k / 4:.1f}</text>')
    for lam in lams:
        parts.append(f'<text x="{lx(lam):.1f}" y="{y0 + H + 17}" font-size="13" fill="#8a8a8a" text-anchor="middle">λ={lam:g}</text>')
    parts.append(f'<text x="{x0 + W / 2:.1f}" y="{Hv - 4}" font-size="13" fill="#8a8a8a" text-anchor="middle">reference-band scale λ (log)</text>')
    # Labels: RMVT above its point, VI50 below its point (2026-09-12, user:
    # "some of the numbers are being overlaid over each other") -- the two
    # curves meet wherever a model sits at the floor or both saturate, and
    # two labels above the same point printed on top of each other.
    for key, color, dy, baseline in (("rmvt", "#f6f6f6", -7, "auto"), ("vi50", "#A9FF3C", 15, "hanging")):
        pts = [(lx(l["lam"]), ly(l[key] if l[key] != float("inf") else ymax)) for l in levels]
        d = " ".join(("M" if i == 0 else "L") + f"{x:.1f},{y:.1f}" for i, (x, y) in enumerate(pts))
        parts.append(f'<path d="{d}" fill="none" stroke="{color}" stroke-width="2"/>')
        for l, (x, y) in zip(levels, pts):
            lab = "∞" if l[key] == float("inf") else f"{l[key]:.2f}"
            parts.append(f'<text x="{x:.1f}" y="{y + dy:.1f}" font-size="13" fill="{color}" text-anchor="middle">{lab}</text>')
    parts.append("</svg>")
    return "\n".join(parts)


SERIES_PAINT = {"truth_render": "#f6f6f6", "truth": "#bdc0b7", "constant_velocity": "#8a8a8a", "copy_last_state": "#5c5c5c"}
MODEL_PAINT = "#A9FF3C"


def _series_color(st, name):
    """The paint's series colours: the model in lime, every comparison series in a grey."""
    return MODEL_PAINT if name == st["model_backend"] else SERIES_PAINT.get(name, "#8a8a8a")


def build_page(st, rsr):
    scenario, model = st["scenario"], st["model_backend"]
    s = st["model_data"]["survival"]
    tmax = float(st["t_max"])
    series = []
    for name in rsr.series_order(st):
        d = rsr.series_data(st, name)
        km = d["survival"]["kaplan_meier"]
        series.append(dict(name=name, color=_series_color(st, name), t=km["t"], S=km["S"],
                           t_end=(km["t"][-1] if km["t"] else 0.0)))
    # model's event rug, grouped by (time, risk)
    grouped = {}
    for e in s["events"]:
        if not e["censored"]:
            k = (round(e["time"], 3), e["risk"]); grouped[k] = grouped.get(k, 0) + 1
    events = [dict(t=t, risk=r, n=n) for (t, r), n in sorted(grouped.items())]
    lh_series, lh_events = [], []
    if st["lh"] is not None:
        for name, block in [(model, st["lh"])] + st["lh_baselines"]:
            km = block["kaplan_meier"]
            lh_series.append(dict(name=name, color=_series_color(st, name), t=km["t"], S=km["S"], t_end=(km["t"][-1] if km["t"] else 0.0)))
        g2 = {}
        for e in st["lh"]["events"]:
            if not e["censored"]:
                k = round(e["time"], 3); g2[k] = g2.get(k, 0) + 1
        lh_events = [dict(t=t, risk="R4", n=n) for t, n in sorted(g2.items())]

    # Shares of EPISODES (not of terminations), same normalization as the
    # PDF's failure-mode chart (2026-09-12): a series that terminated one
    # episode must not read like one that terminated all of them.
    fired = 1.0 - st["censoring"]
    prof = ", ".join(f"{k} {v * fired * 100:.0f}%" for k, v in sorted(st["prof"].items()))
    # Shares of episodes terminated, by channel; nothing else on this card
    # (user, 2026-09-12: a "% valid" clause "makes it sound like none of the
    # results were valid"). Survival at horizons has its own card.
    prof = (prof + " of episodes terminated") if prof else "no terminations"
    S_at = " · ".join(f"S({h}) {v:.2f}" for h, v in st["S_at"].items())
    cards = [("Validity after prefix", f"{rsr.fmt(max(0.0, st['rmvt'] - 1.0))} s", "of the 2 s the model generated"),
             ("VI₅₀", f"{rsr.fmt(st['vi50'])}{'' if st['vi50'] == float('inf') else ' s'}", f"CI [{rsr.fmt(st['ci'][0])}, {rsr.fmt(st['ci'][1])}]"),
             ("RMVT", f"{rsr.fmt(st['rmvt'])} s", "full window, prefix included"),
             ("Episodes", f"{st['n']}", f"censoring {rsr.fmt(st['censoring'])}"),
             ("Failure modes", prof, "share of episodes, by channel"),
             ("Survival at horizons", S_at, "")]
    if st["lh"] is not None:
        cards.append(("R4 long-horizon", f"{(1 - st['lh']['censoring_rate']) * 100:.0f}% fired", f"VI₅₀ {rsr.fmt(st['lh']['vi50'])}"))
    notes = []
    for b, d in st["baselines"]:
        if "recensored_from_t_max" in d:
            notes.append(f"{b} re-censored at {tmax:.2f}s (scored over {d['recensored_from_t_max']:.2f}s)")
    for b in st["missing_baselines"]:
        notes.append(f"{b}: not run for this scenario")
    from mcphysbench.adapters import MODEL_REGISTRY as _REG
    if False and _REG.get(model, {}).get("seed_reproducible", True) is False:   # page no longer states it (user, 2026-10-04); the registry and JSON keep the flag
        notes.append("seed_reproducible = False: the provider accepts no seed, so re-running does not reproduce these videos; "
                     "the comparison is paired on episodes (same prefix and initial condition per seed for every model), "
                     "not on the provider's sampler")
    if "R5" in st.get("channels", []):
        notes.append("theta_R5 is calibrated on this population's own render environment and is not portable across machines")

    import datetime
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    nav = [("summary", "Summary"), ("validity", "Validity"), ("video", "Video"), ("failures", "Failures"), ("readout", "Readout")]
    body = [T.eyebrow(1, "Population", "summary").replace('class="eyebrow"', 'class="kicker"'),
            f"<h1>{html.escape(model)}<span class='sub'>{html.escape(scenario)} · real model vs. ideals and trivial baselines, scored through the same calibrated thresholds</span></h1>",
            T.stats_row([(v, k, sub) for k, v, sub in cards if k not in ("Failure modes", "Survival at horizons")]),
            "<p class='note' style='margin-top:20px'>" + " &nbsp;·&nbsp; ".join(
                f"<span style='color:var(--fg)'>{html.escape(k)}</span> {html.escape(v)}" for k, v, _ in cards if k in ("Failure modes", "Survival at horizons")) + "</p>"]
    if notes:
        body.append(T.noteblock("Notes", "".join(f"<p>{html.escape(n)}</p>" for n in notes)))
    legend = "".join(f'<span style="color:{x["color"]}">{html.escape(x["name"])}</span>' for x in series)
    body += [T.eyebrow(2, "Validity", "validity"), "<h2>Validity over time</h2>",
             '<p class="prose">Kaplan–Meier fraction of episodes still valid. Move along the chart: each series is read out at that instant, and the model\'s most recent drop is named with its diagnosed channel. Ticks along the axis mark every individual model episode\'s event time.</p>',
             '<div class="chart">', _survival_svg("km", series, tmax, events),
             '<div class="readout" id="km-ro"><span class="t">move along the curve</span></div></div>',
             f'<div class="legend">{legend}</div>']
    if lh_series:
        legend2 = "".join(f'<span style="color:{x["color"]}">{html.escape(x["name"])}</span>' for x in lh_series)
        body += ["<h3>R4 long-horizon consistency</h3>",
                 '<p class="prose">Independent channel: cumulative drift below the first-crossing thresholds (CUSUM). Not part of the precedence race above.</p>',
                 '<div class="chart">', _survival_svg("lh", lh_series, tmax, lh_events, height=240),
                 '<div class="readout" id="lh-ro"><span class="t">move along the curve</span></div></div>',
                 f'<div class="legend">{legend2}</div>']
    if st.get("rescore"):
        body += ["<h3>Resolution: VI₅₀ and RMVT vs. reference-band scale</h3>",
                 '<p class="prose">The same cached episodes re-scored against wider reference bands (λ). Where VI₅₀ leaves the floor is where the model becomes rankable; RMVT is defined at every λ.</p>',
                 '<div class="chart">', _lambda_svg(st["rescore"]["levels"]), "</div>",
                 '<div class="legend"><span style="color:#f6f6f6">RMVT (s)</span><span style="color:#A9FF3C">VI₅₀ (s)</span></div>']
    # Generated video (2026-09-12, user: "add the results video/generated
    # video into it so that users can also see how their models are
    # performing beyond just the stats"): the population's own annotated
    # grid (3 episodes side by side) and, when it exists, the instrument
    # ideal's grid for the SAME seeds. Embedded as data URIs (2026-09-12:
    # IDE previews refuse local media through relative file:// paths; a
    # self-contained page has no path to refuse; ~200 KB per video).
    import base64
    vids = []
    for name, label in ((model, f"{model} — continuation"),
                        ("truth_render", "ideal (instrument) — the true continuation, rendered, same seeds")):
        p = ROOT / "results" / "videos" / f"{scenario}_{name}_grid.mp4"
        if p.exists():
            uri = "data:video/mp4;base64," + base64.b64encode(p.read_bytes()).decode("ascii")
            vids.append(f'<figure><div class="stage"><video controls autoplay muted loop playsinline '
                        f'src="{uri}"></video></div><figcaption>{html.escape(label)}</figcaption></figure>')
    body += [T.eyebrow(3, "Video", "video"), "<h2>Model output</h2>"]
    if vids:
        body += ['<p class="prose">Three episodes side by side. Green border: the real rendered prefix the model was conditioned on; red border: the model\'s continuation. '
                 'Green marker: the true object position; red marker: the position Phi reconstructed from the model\'s pixels — the gap between them is what the channels score.</p>',
                 '<div style="display:grid; gap:24px">' + "".join(vids) + "</div>"]
    else:
        body.append('<p class="note">No grid video was rendered for this population.</p>')
    # Failure classification: one divided bar per series, share of episodes.
    bars = []
    for name in rsr.series_order(st):
        d = rsr.series_data(st, name)["survival"]
        bars.append(_stack_bar(d["termination_profile"], d["censoring_rate"], label=rsr.series_label(name), height=24))
    legend3 = "".join(f'<span class="chip"><i style="background:{RISK_COLOR[k]}"></i>{k} {lab}</span>' for k, lab in
                      [("R1", "existence"), ("R2", "interpenetration"), ("R3", "kinematic"), ("R5", "frame"), ("R6", "conservation"), ("R7", "shape")]
                      if k in st.get("channels", [])) + '<span class="chip"><i style="background:#A9FF3C"></i>still valid at t_max</span>'
    body += [T.eyebrow(4, "Failures", "failures"), "<h2>Failure classification</h2>",
             '<p class="prose">Share of episodes terminated by each channel, for the model and every comparison series on this page. The lime remainder never failed a check inside the scored window.</p>',
             '<div class="chart" style="padding:14px 18px">' + "".join(bars) + "</div>", f'<div class="chips">{legend3}</div>']
    rows = "".join(f"<tr><td>{html.escape(l)}</td></tr>" for l in rsr.readout_lines(st))
    body += [T.eyebrow(5, "Readout", "readout"), "<h2>Computed readout</h2>", f"<div class='scroll'><table class='readout-t'>{rows}</table></div>",
             f"<p style='margin-top:28px'><a class='btn outline' href='index.html'>All populations ↗</a> &nbsp; <a class='btn outline' href='leaderboard.html'>Leaderboard ↗</a></p>",
             f"<div class='foot'>{html.escape(PUBLIC_NAME)}</div>"]
    script = (f"{JS}\nattach('km', {json.dumps(series)}, {tmax}, {json.dumps(events)});\n"
              + (f"attach('lh', {json.dumps(lh_series)}, {tmax}, {json.dumps(lh_events)});\n" if lh_series else ""))
    return T.shell(f"{model} · {scenario} — {PUBLIC_NAME}", "index.html", T.nav_items(nav),
                   [("index.html", "Populations"), ("leaderboard.html", "Leaderboard")], "\n".join(body), extra_css=CSS, extra_js=script)


INDEX_CSS = CSS + """
.scene{margin:0 0 40px}
.scene .head{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px 16px;margin:0 0 10px}
.scene .head h3{margin:0}
.scene td.cls{min-width:220px}.scene td.cls .stackrow{margin:0}
.scene .bar{display:inline-block;vertical-align:middle;margin:0 10px 0 0;width:90px}
.scene th,.scene td{padding-right:12px}
.board td.name{white-space:normal;min-width:220px}
.board td.name .tag{display:block;width:max-content;margin:6px 0 0}
.board td.lead{white-space:normal;max-width:360px}
figure.truth figcaption{margin-top:10px}
.board td.num,.board th.r{font-variant-numeric:tabular-nums}
"""


def _video_uri(scenario, name):
    import base64
    p = ROOT / "results" / "videos" / f"{scenario}_{name}_grid.mp4"
    if not p.exists():
        return None
    return "data:video/mp4;base64," + base64.b64encode(p.read_bytes()).decode("ascii")


def _reel(all_stats, rsr):
    """The front-page reel (user, 2026-09-16: "bring some of the videos to
    the front as some visualization thing"): the headline scenario's
    generated clips, one per real model, plus the instrument ideal's clip
    of the same episodes for the eye to compare against. Each tile links
    to its population page. ~200 KB per clip, embedded like the pages'."""
    headline = rsr.HEADLINE_SCENARIO
    tiles = []
    for st in sorted(all_stats, key=lambda s: -s["rmvt"] if s["rmvt"] == s["rmvt"] else 0):
        if st["scenario"] != headline:
            continue
        uri = _video_uri(headline, st["model_backend"])
        if uri is None:
            continue
        vi = rsr.fmt(st["vi50"]) + ("" if st["vi50"] == float("inf") else " s")
        tiles.append(f'<a href="{headline}_{st["model_backend"]}.html"><figure><div class="stage"><video autoplay muted loop playsinline src="{uri}"></video></div>'
                     f'<figcaption><b>{html.escape(st["model_backend"])}</b><span>VI₅₀ {html.escape(vi)} · RMVT {rsr.fmt(st["rmvt"])} s</span></figcaption></figure></a>')
    ideal = _video_uri(headline, "truth_render")
    if ideal is not None:
        tiles.append(f'<figure><div class="stage"><video autoplay muted loop playsinline src="{ideal}"></video></div>'
                     f'<figcaption class="ideal"><b>ideal (instrument)</b><span>true continuation, rendered</span></figcaption></figure>')
    if not tiles:
        return ""
    return (f'<p class="prose">Three episodes side by side per model, on the headline scene <b>{html.escape(headline)}</b>. Green border: the rendered prefix the model saw; red border: its continuation. '
            f'Green marker: the true object; red marker: what Phi reconstructed from the model\'s pixels.</p>'
            f'<div class="reel">{"".join(tiles)}</div>')


def _leaderboard_section():
    """A compact view of results/leaderboard.json (written by render_leaderboard,
    which runs after this in render_score_report): one row per scene with its
    stability verdict and, where ranked, the top row. The full tables live on
    leaderboard.html; nothing here is computed differently."""
    path = ROOT / "results" / "leaderboard.json"
    if not path.exists():
        return "<p class='note'>The leaderboard has not been rendered yet.</p>"
    b = json.loads(path.read_text())
    rows = []
    for scen, sc in b["scenes"].items():
        stab = sc["stability"]
        if sc.get("ranked"):
            badge = "<span class='tag ok'>ranked</span>" + ("<span class='tag err'>band-specific</span>" if sc.get("band_sensitive") else "<span class='tag ok'>general</span>")
            top = [s for s in sc["ranked_order"] if sc["rows"][s].get("rank") == 1 and not sc["rows"][s]["defects"]]
            lead = ", ".join(top) if top else "–"
            r = sc["rows"][top[0]] if top else None
            rmvt = f"{r['rmvt']:.2f} <span class='ci'>[{r['rmvt_ci95'][0]:.2f}, {r['rmvt_ci95'][1]:.2f}]</span>" if r else "–"
        else:
            badge = f"<span class='tag'>unranked · {stab.get('n_models', 0)} rankable cells</span>"
            lead, rmvt = "<span class='ci'>fewer than 3 rankable cells</span>", "–"
        ceil = f"{sc['ceiling_rmvt']:.2f}" if sc.get("ceiling_rmvt") is not None else "–"
        rows.append(f"<tr><td class='name'><a href='leaderboard.html#scene-{html.escape(scen)}'>{html.escape(scen)}</a>{badge}</td>"
                    f"<td class='lead'>{html.escape(lead) if '<' not in lead else lead}</td><td class='num'>{rmvt}</td><td class='num r'>{ceil}</td></tr>")
    return ("<div class='scroll'><table class='board'><thead><tr><th>scene</th><th>rank 1 (ties share it)</th><th>RMVT (s) [95% CI]</th><th class='r'>ceiling RMVT</th></tr></thead><tbody>"
            + "".join(rows) + "</tbody></table></div>"
            f"<p class='note' style='margin-top:14px'>Ranks are dense over significant paired separations within a scene; there is no cross-scene score.</p>"
            "<p style='margin-top:20px'><a class='btn' href='leaderboard.html'>Open the leaderboard ↗</a></p>")


def render_pages(all_stats, omitted=()):
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    import render_score_report as rsr
    ordered = sorted(all_stats, key=lambda s: (rsr.scenario_sort_key(s["scenario"]), s["model_backend"]))
    groups = {}
    tmax_by_scenario = {}
    for st in ordered:
        name = f"{st['scenario']}_{st['model_backend']}.html"
        (PAGES_DIR / name).write_text(build_page(st, rsr))
        vi = rsr.fmt(st["vi50"])
        tmax = float(st["t_max"]); tmax_by_scenario[st["scenario"]] = tmax
        # RMVT as a bar against the episode horizon (a model that stays
        # valid the whole way fills the bar), then the number.
        # Validity after the prefix (2026-10-07): the first second is the given prefix and cannot fail.
        PREFIX_S = 1.0
        ap = max(0.0, st["rmvt"] - PREFIX_S) if st["rmvt"] == st["rmvt"] else float("nan")
        w = max(0.0, min(1.0, ap / (tmax - PREFIX_S))) * 100 if ap == ap else 0.0
        groups.setdefault(st["scenario"], []).append(
            f"<tr><td class='name'><a href='{name}'>{html.escape(st['model_backend'])}</a></td><td class='num r'>{st['n']}</td>"
            f"<td class='num r'>{vi}</td><td class='num'><span class='bar'><i style='width:{w:.0f}%'></i></span>{rsr.fmt(ap)} <span class='ci'>(RMVT {rsr.fmt(st['rmvt'])})</span></td>"
            f"<td class='cls'>{_stack_bar(st['prof'], st['censoring'], height=20)}</td></tr>")
    # Rendered truth beside every scenario (user, 2026-09-16: "update the
    # webpage with the rendered truth"): the instrument ideal's clip sits
    # next to the table so the ceiling every row is judged against is
    # visible, not just a number.
    def _truth_tile(scenario):
        uri = _video_uri(scenario, "truth_render")
        if uri is None:
            return ""
        return (f'<figure class="truth"><div class="stage"><video autoplay muted loop playsinline src="{uri}"></video></div>'
                f'<figcaption><b>rendered truth</b> · the true continuation through the same renderer, codec and tracker</figcaption></figure>')
    sections = "".join(
        f"<section class='scene'><div class='head'><h3>{html.escape(scenario)}</h3></div><div class='split'>"
        f"<div class='scroll'><table><thead><tr><th>model</th><th class='r'>episodes</th><th class='r'>VI₅₀ (s)</th>"
        f"<th>validity after prefix (s) · of {tmax_by_scenario[scenario] - 1:.0f} s</th><th>terminated, by channel</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        f"{_truth_tile(scenario)}</div></section>"
        for scenario, rows in groups.items())
    n_models = len({s["model_backend"] for s in all_stats})
    n_scenes = len(groups)
    n_eps = T.videos_scored(ROOT / "results")   # all-time, superseded versions included (user, 2026-10-05)
    key = "".join(f'<span class="chip"><i style="background:{RISK_COLOR[k]}"></i>{k} {lab}</span>' for k, lab in
                  [("R1", "existence"), ("R2", "interpenetration"), ("R3", "kinematic"), ("R4", "long-horizon"), ("R5", "frame invariance"), ("R6", "conservation"), ("R7", "shape")])
    key += '<span class="chip"><i style="background:#A9FF3C"></i>still valid at t_max</span>'
    scene_rows = [
        ("occlusion_reemergence", "object permanence", "A ball rolls behind an occluder and must come out the other side where physics puts it. The headline scene."),
        ("occlusion_corridor", "object permanence", "A ball travels along a corridor and passes behind a wall; the model must keep it in existence through the gap."),
        ("occlusion_corridor_interpenetration", "contact", "The same corridor, scored for solids passing through solids as the ball reaches the wall."),
        ("ramp_descent", "dynamics", "A ball rolls down an incline; the scored question is whether its motion stays kinematically plausible."),
        ("ramp_descent_high_friction", "dynamics", "The same incline with high friction, so the ball should roll slowly and settle."),
        ("collision", "dynamics", "Two balls collide on a flat floor; momentum and direction after impact are what break."),
        ("billiards", "dynamics", "Several balls, several collisions, on a flat table."),
        ("block_stack", "contact and support", "A stack of blocks that must stay supported and in contact as the scene evolves."),
        ("soft_ramp", "soft body", "A deformable ball rolls down the incline; volume and shape are scored as well as motion."),
    ]
    scene_table = ("<div class='scroll'><table><thead><tr><th>scene</th><th>tests</th><th>what happens</th></tr></thead><tbody>" +
                   "".join(f"<tr><td class='name'>{html.escape(a)}</td><td>{html.escape(b)}</td><td style='white-space:normal;max-width:620px'>{html.escape(c)}</td></tr>"
                           for a, b, c in scene_rows) + "</tbody></table></div>")
    channel_rows = [
        ("R1", "existence", "The tracked object vanishes, duplicates, or fails to re-emerge from behind an occluder where the reference ensemble says it must."),
        ("R2", "interpenetration", "Two solids occupy the same space: the reconstructed geometry overlaps by more than the reference band allows."),
        ("R3", "kinematic", "Position or velocity leaves the band of physically possible trajectories. The most common failure on rigid scenes."),
        ("R4", "long-horizon drift", "A cumulative-sum test on slow drift that never crosses the instantaneous band. Scored on its own, outside the first-failure race."),
        ("R5", "frame invariance", "Static geometry moves in the image: the model has moved the camera or the room. Pixel-level, with a 1 px floor."),
        ("R6", "conservation", "Soft bodies only: the silhouette area drifts outside the band, meaning the body is inflating or losing volume."),
        ("R7", "shape", "Soft bodies only: the axis ratio of the body leaves the band, a deformation the material cannot produce."),
    ]
    channel_table = ("<div class='scroll'><table><thead><tr><th>channel</th><th>name</th><th>what it detects</th></tr></thead><tbody>" +
                     "".join(f"<tr><td class='name'><span class='chip'><i style='background:{RISK_COLOR[k]}'></i>{k}</span></td><td>{html.escape(n)}</td>"
                             f"<td style='white-space:normal;max-width:640px'>{html.escape(d)}</td></tr>" for k, n, d in channel_rows) + "</tbody></table></div>")
    buttons = ("<p style='margin-top:24px'><a class='btn' href='leaderboard.html'>Leaderboard ↗</a> &nbsp; "
               "<a class='btn outline' href='results.html'>Results by scene ↗</a> &nbsp; <a class='btn outline' href='#method'>How it works</a></p>")
    P = html.escape(PUBLIC_NAME)

    # ---- index: stats, the headline videos, then the write-up ----
    nav = [("overview", "Overview"), ("headline", "Headline scene"), ("method", "How it works"), ("channels", "Failure channels"),
           ("ranking", "From episodes to ranks"), ("validation", "Validation"), ("scenes", "Scenes")]
    body = [T.eyebrow(1, "Research", "overview").replace('class="eyebrow"', 'class="kicker"'),
            f"<h1>{P}<span class='sub'>{html.escape(PUBLIC_TAGLINE)}</span></h1>",
            f"<p class='hook'>{P} measures how long a video world model's prediction of a simple physical scene stays physically valid, and names "
            "what breaks first. It is a measuring instrument with published error floors, not a similarity score.</p>",
            T.stats_row([(n_models, "models", "single-image and video-conditioned"), (n_scenes, "scenes", "rigid and soft-body"),
                         (f"{n_eps:,}", "model videos scored", "every episode, every model version"), (f"{tmax_by_scenario.get(rsr.HEADLINE_SCENARIO, 3.0):g} s", "scored window", "per episode")]),
            buttons,
            T.eyebrow(2, "Headline scene", "headline"), "<h2>What the models produce</h2>", _reel(all_stats, rsr),

            T.eyebrow(3, "How it works", "method"), "<h2>One episode, step by step</h2>",
            "<p class='prose'>Video world models are usually judged by how much their output resembles a reference clip. Resemblance is the wrong question "
            "for physics: a clip can look right and still have the ball pass through the wall. "
            f"{P} instead treats the model as a physical predictor and asks the question an experimentalist would ask: "
            "for how long does its prediction stay inside the range of outcomes physics allows, and when it leaves, which law did it break.</p>",
            "<h3>1. A scene is simulated and rendered</h3>",
            "<p class='prose'>Each scene is a rigid- or soft-body simulation with a nominal initial state. One episode is one draw from a perturbation model "
            "around that state: small changes to positions and velocities, scaled by a per-scene factor. The first second of the episode is rendered to a "
            "short video prefix at 30 frames per second. The seed that fixes the perturbation is the same for every model, so every model sees the same 50 episodes.</p>",
            "<h3>2. The model continues it</h3>",
            "<p class='prose'>The model receives the last frame of the prefix and the scene's fixed text prompt, and produces a continuation. This is single-image "
            "conditioning, the same for every model; two video-conditioned arms that see the whole prefix are shown separately and never ranked against the "
            "single-image rows. The continuation is resampled to the scoring resolution and frame rate, then everything after the prefix is scored for two more seconds.</p>",
            "<h3>3. Pixels are measured back into state</h3>",
            "<p class='prose'>A fixed measurement operator turns the video into object state: a promptable segmentation tracker follows each object through "
            "every frame, including through occlusion, and its masks are reconstructed into positions using the scene's known camera and geometry. "
            "No language model is anywhere in this path. The same operator runs on the reference videos, never on simulator state, so the reference "
            "and the candidate carry the same instrument error.</p>",
            "<h3>4. A reference ensemble sets the tolerance</h3>",
            "<p class='prose'>For every episode, the simulator is run many more times from independently perturbed initial conditions, typically 30 and up to 100, "
            "and each run is rendered and measured the same way. How much these physically valid continuations differ from each other defines the tolerance: "
            "for each channel, the threshold is the 99th percentile of reference-versus-reference deviation, so a correct prediction is flagged about one "
            "percent of the time by construction. The band's scale is a declared per-scene parameter, and every ranking is re-checked at half and double that width.</p>",
            "<h3>5. The first sustained violation ends the episode</h3>",
            "<p class='prose'>A crossing must persist for 0.3 seconds to count, which keeps single-frame tracker flicker from ending an episode. "
            "When several channels cross at once the cause is assigned by a fixed precedence, from frame invariance through existence, conservation, "
            "interpenetration, kinematics, and shape, so that a moved camera is never misreported as a moved object. The episode's result is a time and a cause. "
            "An episode that survives the whole window is censored at 3 seconds, a valid outcome rather than a failure.</p>",

            T.eyebrow(4, "Failure channels", "channels"), "<h2>What breaks first</h2>",
            "<p class='prose'>Each channel is a separate detector with its own statistic and its own calibrated threshold. The colours in every bar on this site come from this table.</p>",
            channel_table,

            T.eyebrow(5, "From episodes to ranks", "ranking"), "<h2>Survival analysis, not averages</h2>",
            "<p class='prose'>Fifty episodes give a set of validity times with censoring, which is exactly the shape of data survival analysis was built for. "
            "The Kaplan–Meier estimator turns them into a survival curve: the fraction of episodes still physically valid at each instant. Two summaries are reported.</p>",
            "<p class='prose'><b>RMVT</b>, the restricted mean validity time, is the area under the curve over the 3-second window: the expected number of seconds an "
            "episode stays valid. It is always finite and it is the statistic models are ranked on. The first second of that window is the given prefix, which "
            "cannot fail, so every displayed share of the ceiling and the overall score use the generated window, RMVT minus 1 s over the ceiling's RMVT minus 1 s; "
            "a model that breaks physics on its first generated frame scores about zero. Subtracting the same second from every row changes no ranking. "
            "<b>VI₅₀</b> is the time by which half the episodes have failed. "
            "It is reported on every row but it cannot rank most models, because they fail within a frame or two of the prefix ending and VI₅₀ sits at that floor, "
            "about 1.03 seconds.</p>",
            "<p class='prose'>Uncertainty comes from a percentile bootstrap over episodes. Because every model saw the same 50 episodes, model-to-model comparisons "
            "use a paired bootstrap on the shared seeds, which cancels the episode-level variance and is far more sensitive than comparing two independent "
            "intervals. Within a scene, every adjacent pair in the ordering is tested, with a Holm correction over all pairs, and adjacent rows that cannot be "
            "separated share a rank. A rank is therefore a dense rank over significant separations, not a sort order.</p>",
            "<p class='prose'>Three reference rows sit beside the models on every scene. <b>Constant velocity</b> and <b>copy last state</b> are baselines that extrapolate "
            "the prefix with no model at all; copy last state is the information-matched baseline for a model that sees one frame. The <b>instrument ceiling</b> is the "
            "true simulated continuation rendered through the same renderer, codec and tracker, so it shows the best validity time the measurement itself can award, "
            "and every model's RMVT is also reported as a fraction of it.</p>",
            "<p class='prose'>There is deliberately no overall score. The scenes test different physical properties and their winners differ; a mean across them would "
            "hide which model holds which property and would be dominated by whichever scenes have the highest ceiling. The cross-scene view reports a median rank "
            "with its range and counts against the baselines, and nothing is summed. A scene is ranked at its own band, and if its order changes when the band is "
            "halved or doubled it is flagged band-specific and every row shows its position at all three widths. The ranking rules were written before the full set "
            "of results existed and are reproduced on the leaderboard page; where a rule was amended, the original stays visible with the reason.</p>",

            T.eyebrow(6, "Validation", "validation"), "<h2>How the instrument proves it works</h2>",
            "<p class='prose'>A detector that fires on everything, or on nothing, produces numbers without producing measurements. Every channel here was validated "
            "against planted defects before any model was scored, and every validation result is itself published.</p>",
            "<p class='prose'><b>Determinism.</b> The simulator is checked to reproduce an episode bit for bit from its seed across processes and machines, "
            "so the reference ensemble is the same ensemble wherever it is computed.</p>",
            "<p class='prose'><b>Planted defects.</b> Each scene has a library of mutants: a simulated continuation with a known fault inserted at a known time. "
            "An object that vanishes, teleports, duplicates, freezes mid-flight, or falls under the wrong gravity; for soft bodies, a wrong stiffness, a volume "
            "leak, or a frozen deformation. A scene is admitted only when the null mutant, a clean continuation, fires at the designed false-positive rate or below, "
            "and each fault is caught by the right channel at the right time.</p>",
            "<p class='prose'><b>The instrument tax.</b> The same mutants are then passed through the full video path, rendered and tracked, rather than read from "
            "simulator state. The difference between the two is the cost of measuring through pixels, and it is reported per scene as the instrument ceiling. "
            "Where the tracker cannot see a defect, for instance a shape change smaller than its own noise on a soft body, that floor is recorded rather than hidden.</p>",
            "<p class='prose'><b>Resolution.</b> Every population is re-scored at half, one, and twice its reference band from cached trajectories. Where a model's "
            "validity time leaves the floor as the band widens is where it becomes rankable, and the leaderboard shows that per row.</p>",

            T.eyebrow(7, "Scenes", "scenes"), "<h2>Nine scenes, four properties</h2>",
            "<p class='prose'>Each scene isolates one physical property: object permanence through occlusion, contact between solids, rigid-body dynamics, and soft-body "
            "conservation. The scenes are deliberately simple. If a model cannot keep a rolling ball on its path for three seconds, its behaviour in a richer world "
            "cannot be trusted, and a simple scene is one where the reference ensemble is unambiguous.</p>",
            scene_table,

            buttons,
            f"<div class='foot'>{P}</div>"]
    index = T.shell(PUBLIC_NAME, "index.html", T.nav_items(nav),
                    [("leaderboard.html", "Leaderboard"), ("results.html", "Results"), ("leaderboard.json", "JSON")],
                    "".join(body), extra_css=INDEX_CSS, wide=True)

    # ---- results page: every population, by scene ----
    rnav = [("results", "Results by scene"), ("channels", "Channel key")]
    rbody = [T.eyebrow(1, "Results", "results").replace('class="eyebrow"', 'class="kicker"'),
             f"<h1>Results by scene<span class='sub'>Every population, with the rendered truth it is judged against.</span></h1>",
             "<p class='prose'>One row per model and scene. The first second of every episode is the given prefix and cannot fail, so the headline number is "
             "validity after the prefix, RMVT minus 1 s, with the bar against the 2 s the model generated; the divided bar is the share of episodes each channel "
             "terminated, with the lime remainder still valid at the end of the window. Open a row to trace its survival curve and watch its videos.</p>",
             "<p style='margin-top:20px'><a class='btn' href='leaderboard.html'>Leaderboard ↗</a> &nbsp; <a class='btn outline' href='index.html'>About the benchmark</a></p>",
             sections,
             T.eyebrow(2, "Channel key", "channels"), "<h2>What the colours mean</h2>", channel_table,
             f"<div class='foot'>{P}</div>"]
    results = T.shell(f"Results — {PUBLIC_NAME}", "index.html", T.nav_items(rnav),
                      [("index.html", "About"), ("leaderboard.html", "Leaderboard")], "".join(rbody), extra_css=INDEX_CSS, wide=True)
    (PAGES_DIR / "results.html").write_text(results)
    (PAGES_DIR / "index.html").write_text(index)
    return PAGES_DIR / "index.html"


def main():
    import render_score_report as rsr
    from mcphysbench.adapters import REAL_MODEL_BACKENDS, MODEL_REGISTRY
    from mcphysbench.stats.survival import bootstrap_vi_delta
    from mcphysbench.detect.events import Event
    all_results = rsr.discover_all()
    pages = sorted((s, b) for (s, b) in all_results if b in MODEL_REGISTRY)   # shown regardless of the run opt-in (2026-10-06)
    pages, omitted = rsr.apply_supersession(pages, all_results, MODEL_REGISTRY)
    stats = [rsr.compute_stats(s, b, all_results, bootstrap_vi_delta, Event) for s, b in pages]
    out = render_pages(stats, omitted)
    print(f"-> {out} ({len(stats)} page(s))")


if __name__ == "__main__":
    main()
